### PR TITLE
Feature/enhance multi platform build

### PR DESCRIPTION
**Pull request by developer-guy**
we (w/@dentrax) tried to improve the Dockerfile for the exporter project with builtin BuildKit features.
/cc @sozercan

### CODE REVIEW

**Comment by developer-guy** [comment]
@microsoft-github-policy-service agree [company="Trendyol"]

**Comment by developer-guy** [comment]
@microsoft-github-policy-service agree

**Comment by developer-guy** [comment]
@microsoft-github-policy-service agree

**Comment by developer-guy** [comment]
any luck? @helayoty

**Review by Fei-Guo — APPROVED** [review]

**Pull request merged**
